### ISSUE TITLE
How to make the routing work without locale

### ISSUE THREAD

**Issue by vasilvestre** [BridgeAPI-Io/Plugin-Sylius-Bridge#3]
My application do not use locale in URL for the french (main) channel.
Which means the routing like `/{_locale}/shop/fetch/banks` fails.
The constraints on this route is to user either fr|en but I use fr_FR under the hood.

**Comment by vasilvestre** [comment]
This is how I did :

```
bridge_fetch_banks:
    path:
        fr_FR: /shop/fetch/banks
        en: /{_locale}/shop/fetch/banks
    methods: [GET, POST]
    defaults:
        _controller: bridge.action.fetch_banks

bridge_update_selected_bank_on_payment:
    path:
        fr_FR: /update/bank/payment
        en: /{_locale}/update/bank/payment
    methods: [POST]
    defaults:
        _controller: bridge.action.update_selected_bank_on_payment

bridge_failed_status:
    path:
        fr_FR: /account/order/payment/failed
        en: /{_locale}/account/order/payment/failed
    methods: [GET, POST]
    defaults:
        _controller: bridge.action.failed_status


bridge_plugin_routing:
    resource: "@BridgeSyliusPaymentPlugin/Resources/config/routes.yaml"
```
